#!/usr/bin/env bash
# okey lwt's install nginx and configure it
sudo apt update
sudo apt -y install nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx start
sudo chmod -R 775 /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo nginx -s reload
