#!/usr/bin/env bash
#This script displays:
#The x of the current directory In a list format
#Where only the part of the name after the first dash is displayed
x=$(ls)
for i in $x
do
    echo "$i" | cut -d "-" -f2
done
